language: bash

env:
  - SHUNIT_COLOR='always'

script:
  # Run shFlags unit tests.
  - ./shflags_test.sh

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - ksh
      - zsh

matrix:
  include:
    - os: linux
      script:
        # Run the source through ShellCheck (http://www.shellcheck.net).
        - shellcheck gen_test_results.sh
        #- shellcheck shflags shflags_test_*.sh
        #- shellcheck -s sh shflags_test_helpers
